name: test
on: [push]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
#    - run: go test -v ./bls
    - run: git submodule update --init --recursive
    - name: build on Windows
      if: runner.os == 'Windows'
      run: |
        go checkout -b release
        go test -v ./bls

